title: Chris Leung
url: "https://leungchristopher.com"
email: chcl4@cam.ac.uk
description: Machine learning and genetics at Cambridge.
github_username: leungchristopher

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  input: GFM
  hard_wrap: false

permalink: /blog/:title/

collections:
  books:
    output: true
    permalink: /books/:title/

include:
  - _pages

plugins:
  - jekyll-feed
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: page
  - scope:
      path: ""
      type: books
    values:
      layout: book
